version: '3'

services:
  centor-server-1:
    build:
      context: .
    command: --api
    networks:
      - cluster
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - SERVER=true
      - LEADER=true
      - NAME=ali
    ports:
      - "9090:9090"

  centor-server-2:
    build:
      context: .
    networks:
      - cluster
    environment:
      - HOST=0.0.0.0
      - PORT=3002
      - SERVER=true
      - JOIN=centor-server-1:3000
      - ALTERNATIVE_HOST=centor-server-2
      - NAME=reza
   
  

  centor-client-1:
    build:
      context: .
    networks:
      - cluster
    environment:
      - PORT=4001
      - JOIN=centor-server-1:3000,centor-server-2:3002
      - ALTERNATIVE_HOST=centor-client-1
      - NAME=client-1
    depends_on:
      - centor-server-1   
      - centor-server-2   

  centor-client-2:
    build:
      context: .
    networks:
      - cluster
    environment:
      - PORT=4002
      - JOIN=centor-server-1:3000,centor-server-2:3002
      - ALTERNATIVE_HOST=centor-client-2
      - NAME=client-2
    depends_on:
      - centor-server-1   
      - centor-server-2  
 

  centor-client-3:
    build:
      context: .
    networks:
      - cluster
    environment:
      - PORT=4003
      - JOIN=centor-server-1:3000,centor-server-2:3002
      - ALTERNATIVE_HOST=centor-client-3
      - NAME=client-3
    depends_on:
      - centor-server-1   
      - centor-server-2  
   

networks:
  cluster:
    # Use a custom driver
    driver: bridge